### ISSUE TITLE
Bug: `enableJsonFlag` flag not working with flags and/or args?

### ISSUE THREAD

**Issue by wataruian** [oclif/core#745] opened 2023-03-27 07:34 UTC
Do you want to request a *feature* or report a *bug*?
------------------------------
Bug

What is the current behavior?
-----------------------------
When combining `enableJsonFlag` with `Flags` and/or `Args` the cli fails. Can easily be reproduced via sample code:

```
import { Command, Flags } from '@oclif/core';

export default class Test extends Command {
  public static override enableJsonFlag = true;

  static override flags = {
    testFlag: Flags.string({
      char: 't',
      description: 'Some test flag',
      default: 'Some default value',
    }),
  };

  public async run(): Promise<{ message: string }> {
    const { flags } = await this.parse(Test);

    console.log('hello, world!');
    console.log(flags);

    return { message: 'hello, world!' };
  }
}
```

* If the command is invoked **WITHOUT** the flag `--json` it will not fail

Output:
```
hello, world!
{ testFlag: 'Some default value' }
```

* If the command is invoked **WITH** the flag `--json` it will fail (exit code 2)

Error:
```
{
  "error": {
    "oclif": {
      "exit": 2
    },
    "parse": {
      "input": {
        "argv": [
          "--json"
        ],
        "context": {
          "argv": [
            "--json"
          ],
          ...
          ...
          ...
}
```

The above error is too long and just displays the structure of my whole application/project along with all the other commands defined on it

* If the flag is removed/commented out like this, the `--json` flag will be working fine:

```
public async run(): Promise<{ message: string }> {
    // const { flags } = await this.parse(Test);

    console.log('hello, world!');
    // console.log(flags);

    return { message: 'hello, world!' };
  }
```

Output:
```
hello, world!
{
  "message": "hello, world!"
}
```

What is the expected behavior?
------------------------------
The command should work on all scenarios

Versions
------------------------------
@oclif/core: ^2.7.1
Node Version: 18.15.0
Yarn Version: 3.5.0
OS: MacOS 13.1 (Ventura) M1

**Comment by mdonnalley** [comment] 2023-07-25 20:38
@wataruian Are you still experiencing this on the latest version of oclif/core? I tried reproducing the issue but it's working as expected for me

**Comment by mdonnalley** [comment] 2023-08-07 15:45
@wataruian Are you targeting `ES2022` in your tsconfig? I'm wondering if it's related to [this](https://github.com/oclif/oclif/issues/1100#issuecomment-1454910926) 

Could provide a repository that I can use to recreate the issue? Thanks

**Comment by mdonnalley** [comment] 2023-08-09 16:42
@wataruian I traced it down to this tsconfig setting: `useDefineForClassFields`. Removing that should allow you to use the json flag.

The [docs for useDefineForClassFields](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier) have this line in them:

>This can cause quite a bit of fallout for existing code that use inheritance. First of all, set accessors from base classes won’t get triggered - they’ll be completely overwritten.

We use a setter to insert the `--json` flag whenever `enableJsonFlag` is set so my hypothesis is that the `useDefineForClassFields` behavior prevents this from running, which means the `--json` flag is never added, which means that oclif thinks it's a non-existent flag at runtime

I think we'd resolve this issue by resolving https://github.com/oclif/oclif/issues/1100 since that one is caused by using setters/getters

**Comment by mdonnalley** [comment] 2023-08-09 21:24
@wataruian I _think_ that it might but I can't guarantee it. I'll keep this issue open in the meantime - just in case

**Closed** 2023-09-08 21:12 UTC
