### ISSUE TITLE
Cannot use arguments starting with '-'

### ISSUE THREAD

**Issue by rpastro** [oclif/core#600] opened 2023-01-24 23:05 UTC
**Describe the bug**
With @oclif/core v2 we can no longer pass attribute values starting with a '-', like for instance a negative number.

**To Reproduce**
Create a `coordinates:add` command with the following arguments:
```
    static args = {
        name: Args.string({
            required: true,
            description: 'Coordinate name'
        }),
        longitude: Args.string({
            required: true,
            description: 'Longitude'
        }),
        latitude: Args.string({
            required: true,
            description: 'Latitude'
        })
    };
```

Try adding a negative longitude or negative latitude and you'll get a `Non existent flag` error:
```
coordinates:add "Some coordinate" "-119.1949853" "34.14986578"
 ›   Error: Nonexistent flag: -119.1949853

coordinates:add "Some coordinate" "119.1949853" "-34.14986578"
 ›   Error: Nonexistent flag: -34.14986578
```

This used to work properly with @oclif/code v1.

**Expected behavior**
@oclif/core should accept attribute values starting with a '-' when enclosed in quotes since that should make it clear that this is not a flag.

**Environment (please complete the following information):**
 - OS & version: MacOS Monterey
 - Shell/terminal & version: zsh 5.8.1

**Comment by mdonnalley** [comment] 2023-01-24 23:45
@rpastro Thanks for the issue. The regression is caused by a change we made to assume that anything starting with a hyphen must be flag. By making that assumption we could start throwing errors for misspelled flags on commands with arguments. For instance, v1 would not throw an error if you did `coordinates:add "Some coordinate" "-119.1949853" "34.14986578" --hekp` (help is misspelled here) but v2 can and does throw an error. We have this documented in the [migration guide](https://github.com/oclif/core/blob/main/MIGRATION.md#flag-and-arg-parsing)

However this is a valid use case for arguments starting with hyphens. I just put up a PR that allows for arguments to be negative numbers. The PR will likely get reviewed/merged over the course of the next day

**Closed** 2023-01-25 13:58 UTC
