### ISSUE TITLE
Adding plugins from GitHub/Gitlab repositories

### ISSUE THREAD

**Issue by rhumbertgz** [oclif/core#548] opened 2022-11-04 14:37 UTC
**Describe the bug**
Installing a plugin from a Github/Gitlab _manually_ or using the _plugin-plugins_ doesn't work.

**To Reproduce**

1. Create a new Cli
`npx oclif generate mynewcli`

2. Add Github dependency (it is just a fork without any change)
`yarn add https://github.com/rhumbertgz/plugin-commands.git`

As result:
```
"dependencies": {
    "@oclif/core": "^1.19.1",
    "@oclif/plugin-commands": "https://github.com/rhumbertgz/plugin-commands.git",
    "@oclif/plugin-help": "^5"
  },
```

2. Register plugin
```
"oclif": {
    "bin": "chm",
    "dirname": "chm",
    "commands": "./dist/commands",
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-plugins",
     "@oclif/plugin-commands"
    ]
  }, 
```

**Screenshots**
After running the --help the new "commands" command doesn't appear

![image](https://user-images.githubusercontent.com/10393245/200000505-77d9d092-03b9-4673-9855-ca588b1ce034.png)

**Environment (please complete the following information):**
 - OS & version: [MacOS Monterey 12.6.1 (21G217)]
 - Shell/terminal & version [ zsh 5.8.1 (x86_64-apple-darwin21.0) ]
 - oclif 3.2.24

**Comment by mdonnalley** [comment] 2022-11-04 15:01
@rhumbertgz Thanks for creating the issue.

The problem is that when you install from github, gitlab, or a local project (using `yarn add file:...`) the dependency is added as a pure typescript project with no compiled javascript.

If you're doing this for local development purposes, I would suggest cloning the repo, building it, and then using `yarn link` to add the dependency to your project.

If you absolutely must import from github, you can update the `bin/dev` script to have ts-node to not ignore the oclif plugins inside of node_modules, .e.g

```typescript
require('ts-node').register({project, ignore: ['/node_modules/(?!@oclif/plugin-*)']})
```

However, I'd encourage you to steer away from that solution if possible.

This ts-node issue goes into more depth on the issue of having pure typescript modules in node_modules if you're interested: https://github.com/TypeStrong/ts-node/issues/155

I'm going to close this issue for now but feel free to reopen if you think there's more to this than what I found.

**Closed by mdonnalley** 2022-11-04 15:01 UTC

**Comment by rhumbertgz** [comment] 2022-11-04 15:27
@mdonnalley thanks for reaching out with the explanation. I just installed private registry (Verdaccio) to make my development easier
