### ISSUE TITLE
if a command has a flag with `multiple:true` it will not error out on a non-existent flag (the non-existent flag ends up as the arg)

### ISSUE THREAD

**Issue by shazron** [oclif/core#505] opened 2022-09-30 08:14 UTC
**Describe the bug**
I have a command that has 1 arg, and 1 multiple flag. If I specify a non-existent flag to the command only, that non-existent flag is read as an arg. May be related to #496 

**To Reproduce**
```javascript
const { Command, Flags } = require('@oclif/core')

class FlagsTestCommand extends Command {
  async run () {
    const { args, flags } = await this.parse(FlagsTestCommand)

    this.log('args.path', args.path)
    this.log('flags.myflags', flags.myflags)
  }
}
FlagsTestCommand.description = `issue 496 in oclif/core`

FlagsTestCommand.flags = {
  myflags: Flags.string({
    description: 'my flag for testing',
    char: 'm',
    multiple: true
  })
}

FlagsTestCommand.args = [
  {
    name: 'path',
    description: 'Path to the test directory',
    default: '.'
  }
]

module.exports = FlagsTestCommand
```

run:
1. `oclif FlagsTest --does-not-exist` (args is `--does-not-exist`, when it should error instead)

**Expected behavior**
A non-existent flag should result in an error.

**Actual behavior**
A non-existent flag ends up as the arg value.

**Workaround**
None.

**Comment by mdonnalley** [comment] 2022-10-06 20:07
duplicate of https://github.com/oclif/core/issues/496

**Closed by mdonnalley** 2022-10-06 20:07 UTC

**Comment by shazron** [comment] 2022-10-07 04:04
is it a duplicate though? I'm not even using the `multiple:true` flag, and it eats up args, whereas the other bug is if I used the multiple flag.

**Comment by shazron** [comment] 2023-02-22 02:08
@mdonnalley this is not a duplicate, as I argued above. Can you re-open this? A non-existent flag will not error out because of the multiple:true flag, even if the multiple:true flag is not used. It should error out.
